#docker run --link YOUR_ELASTICSEARCH_CONTAINER_NAME_OR_ID:elasticsearch -p 5601:5601 {docker-repo}:{version}
#
version: '3'
services:
  kibaba:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk

networks:
  elk:
    external: true
