#docker run -d -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" --naame test_es docker.elastic.co/elasticsearch/elasticsearch:7.6.2
#
version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    build:
      context: .
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      #bootstrap.memory_lock: "true" # 因swarm不支援ulimit故單設定這個也沒用
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    #ulimit:# swarm 不支援ulimit
      #memlock:
      #  soft: -1
      #  hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elk

volumes:
  es_data:
    driver: local

networks:
  elk:
    name: elk
    driver: overlay
    attachable: true

x-settings:
  deploy:
    stack_name: elasticsearch
    enable: true
    priority: "100"
  build:
    enable: true
