#docker run --rm -it -v ~/pipeline/:/usr/share/logstash/pipeline/ docker.elastic.co/logstash/logstash:7.6.2
#
version: '3'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    container_name: logstash
    hostname: logstash
    #volumes:
    #  - ./pipeline/:/usr/share/logstash/pipeline/
    networks:
      - elk

volumes:
  es_data:
    driver: local

networks:
  elk:
    external: true

