#docker run --rm -it -v ~/pipeline/:/usr/share/logstash/pipeline/ docker.elastic.co/logstash/logstash:7.6.2
#
version: '3.7'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    container_name: logstash
    hostname: logstash
    volumes:
      - ./pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk

volumes:
  es_data:
    driver: local

networks:
  elk:
    name: elk
    external: true

x-settings:
  deploy:
    stack_name: logstash
    enable: true
    priority: "300"

