#docker run -d -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" --naame test_es docker.elastic.co/elasticsearch/elasticsearch:7.6.2
#
version: '3'
services:
  logstash:
    image: docker.elastic.co/elasticsearch/logstash:7.6.2
    container_name: logstash
    hostname: logstash
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elastic

volumes:
  es_data:
    driver: local

networks:
  elastic:
    driver: bridge

